[GLOBAL]
pants_version = "2.11.0"
backend_packages = [
  "pants.backend.shell",
  "pants.backend.python",
  "pants.backend.python.lint.black",
]

[source]
root_patterns = [
  '/src/python',
]



[anonymous-telemetry]
enabled = true
repo_id = "3252D842-7A7F-4672-8383-E4E040A46946"
